package org.unallied.mmocraft;

public enum ImageID {
    LOGIN_SCREEN, TEXTCTRL_LOGIN_NORMAL, TEXTCTRL_LOGIN_HIGHLIGHTED
    , TEXTCTRL_LOGIN_SELECTED, BUTTON_LOGIN_NORMAL, BUTTON_LOGIN_HIGHLIGHTED
    , BUTTON_LOGIN_SELECTED;
}
