package org.unallied.mmocraft.client;

public enum ImageID {
    LOGIN_SCREEN, TEXTCTRL_LOGIN_NORMAL, TEXTCTRL_LOGIN_HIGHLIGHTED, 
    TEXTCTRL_LOGIN_SELECTED, BUTTON_LOGIN_NORMAL, BUTTON_LOGIN_HIGHLIGHTED,
    BUTTON_LOGIN_SELECTED, BLOCK_DIRT, BLOCK_STONE, BLOCK_IRON, BLOCK_AIR, 
    BLOCK_CLAY, BLOCK_GRAVEL, BLOCK_SANDSTONE, BLOCK_SAND, BACKGROUND_SKY, 
    BUTTON_REGISTER_NORMAL, BUTTON_REGISTER_HIGHLIGHTED, 
    BUTTON_REGISTER_SELECTED, BUTTON_BACK_NORMAL, BUTTON_BACK_HIGHLIGHTED,
    BUTTON_BACK_SELECTED, TEXTCTRL_CHAT_NORMAL, TEXTCTRL_CHAT_HIGHLIGHTED,
    TEXTCTRL_CHAT_SELECTED, BACKGROUND_DIRT, BACKGROUND_SKY_DIRT_INTERSECT, 
    BLOCK_GRASS, BUTTON_CLOSE_NORMAL, BUTTON_CLOSE_HIGHLIGHTED, 
    BUTTON_CLOSE_SELECTED, TOGGLEBUTTON_TOOLBARINVENTORY_NORMAL, 
    TOGGLEBUTTON_TOOLBARINVENTORY_HIGHLIGHTED, 
    TOGGLEBUTTON_TOOLBARINVENTORY_SELECTED, 
    TOGGLEBUTTON_TOOLBARCHARACTER_NORMAL, 
    TOGGLEBUTTON_TOOLBARCHARACTER_HIGHLIGHTED, 
    TOGGLEBUTTON_TOOLBARCHARACTER_SELECTED;
}
