package org.unallied.mmocraft.client;

public enum SpriteID {
    SWORD_IDLE, SWORD_WALK, SWORD_RUN, SWORD_JUMP, SWORD_FALL, 
    SWORD_HORIZONTAL_ATTACK, SWORD_HORIZONTAL_ATTACK_ARC, SWORD_ROLL, 
    SWORD_SHIELD, SWORD_HORIZONTAL_ATTACK_2, SWORD_HORIZONTAL_ATTACK_2_ARC

}
