package org.unallied.mmocraft.client;

public enum SpriteID {
    //Sword
    SWORD_IDLE, SWORD_WALK, SWORD_RUN, SWORD_JUMP, SWORD_FALL, 
    SWORD_HORIZONTAL_ATTACK, SWORD_HORIZONTAL_ATTACK_ARC, SWORD_ROLL, 
    SWORD_SHIELD, SWORD_HORIZONTAL_ATTACK_2, SWORD_HORIZONTAL_ATTACK_2_ARC, 
    SWORD_BACK_AIR_ARC, SWORD_DASH_ATTACK_ARC, SWORD_DOWN_SMASH_ARC, 
    SWORD_FLOOR_ATTACK_ARC, SWORD_FRONT_AIR_ARC, SWORD_NEUTRAL_AIR_ARC, 
    SWORD_SIDE_SMASH_ARC, SWORD_UP_AIR_ARC, SWORD_UP_SMASH_ARC, 
    SWORD_AIR_DODGE, SWORD_BACK_AIR, SWORD_DASH_ATTACK, SWORD_DOUBLE_JUMP, 
    SWORD_DOWN_SMASH, SWORD_FLOOR_ATTACK, SWORD_FRONT_AIR, SWORD_NEUTRAL_AIR, 
    SWORD_SIDE_SMASH, SWORD_SIDESTEP, SWORD_UP_AIR, SWORD_UP_SMASH, 
    SWORD_HELPLESS, 
    
    // Monster
    MONSTER_BUNNY_IDLE, MONSTER_BUNNY_WALK, MONSTER_BUNNY_ATTACK,
    
}
